#https://www.youtube.com/watch?v=43Z13DS_emQ 
setwd("~/cloud-data/cloud-pipeline-tim-tri-culture-storage/Drew_Macklin")
library(Seurat, lib.loc = "/opt/R/site_lib/RLib_Common/4.0.0")

files<-list.files("GSE148822_RAW")

a<-Read10X(paste0("GSE148822_RAW/", files[1]))
b<-Read10X(paste0("GSE148822_RAW/", files[2]))
c<-Read10X(paste0("GSE148822_RAW/", files[3]))
d<-Read10X(paste0("GSE148822_RAW/", files[4]))
e<-Read10X(paste0("GSE148822_RAW/", files[5]))
f<-Read10X(paste0("GSE148822_RAW/", files[6]))
g<-Read10X(paste0("GSE148822_RAW/", files[7]))
h<-Read10X(paste0("GSE148822_RAW/", files[8]))
i<-Read10X(paste0("GSE148822_RAW/", files[9]))
j<-Read10X(paste0("GSE148822_RAW/", files[10]))
k<-Read10X(paste0("GSE148822_RAW/", files[11]))
l<-Read10X(paste0("GSE148822_RAW/", files[12]))
m<-Read10X(paste0("GSE148822_RAW/", files[13]))
n<-Read10X(paste0("GSE148822_RAW/", files[14]))
o<-Read10X(paste0("GSE148822_RAW/", files[15]))
p<-Read10X(paste0("GSE148822_RAW/", files[16]))
q<-Read10X(paste0("GSE148822_RAW/", files[17]))
r<-Read10X(paste0("GSE148822_RAW/", files[18]))
s<-Read10X(paste0("GSE148822_RAW/", files[19]))
t<-Read10X(paste0("GSE148822_RAW/", files[20]))
u<-Read10X(paste0("GSE148822_RAW/", files[21]))
v<-Read10X(paste0("GSE148822_RAW/", files[22]))
w<-Read10X(paste0("GSE148822_RAW/", files[23]))
x<-Read10X(paste0("GSE148822_RAW/", files[24]))
y<-Read10X(paste0("GSE148822_RAW/", files[25]))
z<-Read10X(paste0("GSE148822_RAW/", files[26]))
aa<-Read10X(paste0("GSE148822_RAW/", files[27]))
ab<-Read10X(paste0("GSE148822_RAW/", files[28]))
ac<-Read10X(paste0("GSE148822_RAW/", files[29]))
ad<-Read10X(paste0("GSE148822_RAW/", files[30]))
ae<-Read10X(paste0("GSE148822_RAW/", files[31]))
af<-Read10X(paste0("GSE148822_RAW/", files[32]))
ag<-Read10X(paste0("GSE148822_RAW/", files[33]))
ah<-Read10X(paste0("GSE148822_RAW/", files[34]))
ai<-Read10X(paste0("GSE148822_RAW/", files[35]))
aj<-Read10X(paste0("GSE148822_RAW/", files[36]))

ba<-CreateSeuratObject(counts = a, project = "a", min.cells = 3, min.features = 200)
bb<-CreateSeuratObject(counts = b, project = "b", min.cells = 3, min.features = 200)
bc<-CreateSeuratObject(counts = c, project = "c", min.cells = 3, min.features = 200)
bd<-CreateSeuratObject(counts = d, project = "d", min.cells = 3, min.features = 200)
be<-CreateSeuratObject(counts = e, project = "e", min.cells = 3, min.features = 200)
bf<-CreateSeuratObject(counts = f, project = "f", min.cells = 3, min.features = 200)
bg<-CreateSeuratObject(counts = g, project = "g", min.cells = 3, min.features = 200)
bh<-CreateSeuratObject(counts = h, project = "h", min.cells = 3, min.features = 200)
bi<-CreateSeuratObject(counts = i, project = "i", min.cells = 3, min.features = 200)
bj<-CreateSeuratObject(counts = j, project = "j", min.cells = 3, min.features = 200)
bk<-CreateSeuratObject(counts = k, project = "k", min.cells = 3, min.features = 200)
bl<-CreateSeuratObject(counts = l, project = "l", min.cells = 3, min.features = 200)
bm<-CreateSeuratObject(counts = m, project = "m", min.cells = 3, min.features = 200)
bn<-CreateSeuratObject(counts = n, project = "n", min.cells = 3, min.features = 200)
bo<-CreateSeuratObject(counts = o, project = "o", min.cells = 3, min.features = 200)
bp<-CreateSeuratObject(counts = p, project = "p", min.cells = 3, min.features = 200)
bq<-CreateSeuratObject(counts = q, project = "q", min.cells = 3, min.features = 200)
br<-CreateSeuratObject(counts = r, project = "r", min.cells = 3, min.features = 200)
bs<-CreateSeuratObject(counts = s, project = "s", min.cells = 3, min.features = 200)
bt<-CreateSeuratObject(counts = t, project = "t", min.cells = 3, min.features = 200)
bu<-CreateSeuratObject(counts = u, project = "u", min.cells = 3, min.features = 200)
bv<-CreateSeuratObject(counts = v, project = "v", min.cells = 3, min.features = 200)
bw<-CreateSeuratObject(counts = w, project = "w", min.cells = 3, min.features = 200)
bx<-CreateSeuratObject(counts = x, project = "x", min.cells = 3, min.features = 200)
by<-CreateSeuratObject(counts = y, project = "y", min.cells = 3, min.features = 200)
bz<-CreateSeuratObject(counts = z, project = "z", min.cells = 3, min.features = 200)
baa<-CreateSeuratObject(counts = aa, project = "aa", min.cells = 3, min.features = 200)
bab<-CreateSeuratObject(counts = ab, project = "ab", min.cells = 3, min.features = 200)
bac<-CreateSeuratObject(counts = ac, project = "ac", min.cells = 3, min.features = 200)
bad<-CreateSeuratObject(counts = ad, project = "ad", min.cells = 3, min.features = 200)
bae<-CreateSeuratObject(counts = ae, project = "ae", min.cells = 3, min.features = 200)
baf<-CreateSeuratObject(counts = af, project = "af", min.cells = 3, min.features = 200)
bag<-CreateSeuratObject(counts = ag, project = "ag", min.cells = 3, min.features = 200)
bah<-CreateSeuratObject(counts = ah, project = "ah", min.cells = 3, min.features = 200)
bai<-CreateSeuratObject(counts = ai, project = "ai", min.cells = 3, min.features = 200)
baj<-CreateSeuratObject(counts = aj, project = "aj", min.cells = 3, min.features = 200)

library(ggplot2)
library(tidyverse)
library(gridExtra)

merged<-merge(ba, c(bb, bc, bd, be, bf, bg, bh, bi, bj, bk, bl, bm, bn, bo, bp, bq, br, bs, bt, bu, bv, bw, bx, by, bz, baa, bab, bac, bad, bae, baf, bag, bah, bai, baj))
print(length(unique(rownames(merged@meta.data))))

merged[["percent.mt"]] <- PercentageFeatureSet(merged, pattern = "^MT-")
merged_seurat_filtered <- subset(merged, subset = nCount_RNA > 800 & nFeature_RNA > 500 & percent.mt < 5)
rm(list=setdiff(ls(), "merged_seurat_filtered"))

merged_seurat_filtered <- NormalizeData(object = merged_seurat_filtered)
merged_seurat_filtered <- FindVariableFeatures(object = merged_seurat_filtered)
merged_seurat_filtered <- ScaleData(object = merged_seurat_filtered)
merged_seurat_filtered <- RunPCA(object = merged_seurat_filtered)
merged_seurat_filtered <- FindNeighbors(object = merged_seurat_filtered, dims = 1:15)
merged_seurat_filtered <- FindClusters(object = merged_seurat_filtered, resolution = 0.1)
merged_seurat_filtered <- RunUMAP(object = merged_seurat_filtered, dims = 1:15)

p1 <- DimPlot(merged_seurat_filtered, reduction = 'umap', group.by = "orig.ident", raster = FALSE)
p1

saveRDS(merged_seurat_filtered, file = "GSE148822_RAW/seurat.rds")
merged_seurat_filtered <- readRDS(file = "GSE148822_RAW/seurat.rds")

#do the following if you need to do batch correction
obj.list <- SplitObject(merged_seurat_filtered, split.by = 'orig.ident')
for(i in 1:length(obj.list)){
  obj.list[[i]] <- NormalizeData(object = obj.list[[i]])
  obj.list[[i]] <- FindVariableFeatures(object = obj.list[[i]])
}

features <- SelectIntegrationFeatures(object.list = obj.list)
anchors <- FindIntegrationAnchors(object.list = obj.list, anchor.features = features)
seurat.integrated <- IntegrateData(anchorset = anchors)
seurat.integrated <- ScaleData(object = seurat.integrated)
seurat.integrated <- RunPCA(object = seurat.integrated)
seurat.integrated <- RunUMAP(object = seurat.integrated, dims = 1:15)
saveRDS(seurat.integrated, file = "GSE148822_RAW/seurat.rds")

p2 <- DimPlot(seurat.integrated, reduction = 'umap', group.by = 'orig.ident', raster = FALSE)
p3 <- DimPlot(seurat.integrated, reduction = 'umap', raster = FALSE)
grid.arrange(p2, p3, ncol = 2)

#do the following if you need to manually label cell type clusters
ad.markers <- FindAllMarkers(seurat.integrated, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
ad.markers %>%
  group_by(cluster) %>%
  slice_max(n = 2, order_by = avg_log2FC)

zero<-subset(ad.markers, ad.markers$cluster==0)
one<-subset(ad.markers, ad.markers$cluster==1)
two<-subset(ad.markers, ad.markers$cluster==2)
three<-subset(ad.markers, ad.markers$cluster==3)
four<-subset(ad.markers, ad.markers$cluster==4)
five<-subset(ad.markers, ad.markers$cluster==5)
six<-subset(ad.markers, ad.markers$cluster==6)
seven<-subset(ad.markers, ad.markers$cluster==7)
eight<-subset(ad.markers, ad.markers$cluster==8)
nine<-subset(ad.markers, ad.markers$cluster==9)
ten<-subset(ad.markers, ad.markers$cluster==10)
eleven<-subset(ad.markers, ad.markers$cluster==11)
twelve<-subset(ad.markers, ad.markers$cluster==12)
thirteen<-subset(ad.markers, ad.markers$cluster==13)
fourteen<-subset(ad.markers, ad.markers$cluster==14)
fifteen<-subset(ad.markers, ad.markers$cluster==15)

#saveRDS(seurat.integrated, file = "GSE148822_RAW/seurat.rds")
write.csv(zero, "GSE148822_RAW/zero")
write.csv(one, "GSE148822_RAW/one")
write.csv(two, "GSE148822_RAW/two")
write.csv(three, "GSE148822_RAW/three")
write.csv(four, "GSE148822_RAW/four")
write.csv(five, "GSE148822_RAW/five")
write.csv(six, "GSE148822_RAW/six")
write.csv(seven, "GSE148822_RAW/seven")
write.csv(eight, "GSE148822_RAW/eight")
write.csv(nine, "GSE148822_RAW/nine")
write.csv(ten, "GSE148822_RAW/ten")
write.csv(eleven, "GSE148822_RAW/eleven")
write.csv(twelve, "GSE148822_RAW/twelve")
write.csv(thirteen, "GSE148822_RAW/thirteen")
write.csv(fourteen, "GSE148822_RAW/fourteen")
write.csv(fifteen, "GSE148822_RAW/fifteen")

#https://www.proteinatlas.org/ENSG00000107099-DOCK8/single+cell+type
seurat.integrated <- RenameIdents(seurat.integrated, '0' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '1' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '2' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '3' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '4' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '5' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '6' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '7' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '8' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '9' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '10' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '11' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '12' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '13' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '14' = '')
seurat.integrated <- RenameIdents(seurat.integrated, '15' = '')

p4<-DimPlot(seurat.integrated, reduction = 'umap')
grid.arrange(p3, p4, ncol = 2)

seurat.integrated[["celltype"]]<-Idents(seurat.integrated)
seurat_clustered<- subset(seurat.integrated, subset = celltype %in% c("Astrocytes", "Microglia", "Inhibitory Neuron", "Excitatory Neuron", "OPC", "Oligodendrocyte"))
p5 <- DimPlot(seurat_clustered, reduction = 'umap')
#saveRDS(seurat_clustered, file = "datasets/AD_WBrain_PMID35260865_H/seurat_object/seurat_final.rds")
